<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625045939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bakery (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, money DOUBLE PRECISION NOT NULL, reputation INT NOT NULL, day INT NOT NULL, orders_completed INT NOT NULL, orders_failed INT NOT NULL, inventory JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cake (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, size VARCHAR(255) NOT NULL, layers INT NOT NULL, frosting_flavor VARCHAR(255) NOT NULL, toppings TEXT DEFAULT NULL, quality_score DOUBLE PRECISION DEFAULT NULL, is_baked BOOLEAN NOT NULL, cake_order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FA13015DED732CB ON cake (cake_order_id)');
        $this->addSql('CREATE TABLE cake_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, due_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payout DOUBLE PRECISION NOT NULL, happiness_bonus INT NOT NULL, customer_name VARCHAR(255) NOT NULL, avatar VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE cake ADD CONSTRAINT FK_FA13015DED732CB FOREIGN KEY (cake_order_id) REFERENCES cake_order (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cake DROP CONSTRAINT FK_FA13015DED732CB');
        $this->addSql('DROP TABLE bakery');
        $this->addSql('DROP TABLE cake');
        $this->addSql('DROP TABLE cake_order');
    }
}
